Feature/#106 refactor bookshelf device
team-peekabook/Peekabook-AOS pull request #110
Opened 2023-02-23 09:07 UTC by stellar-halo

관련 이슈
- closed #105 #106 

작업 사진/동영상 (선택)
-인터넷 미연결시
![image](https://user-images.githubusercontent.com/91793891/220862709-870602ff-337a-4f0e-ba6d-4177c9714cbf.png)
-s10
![s10](https://user-images.githubusercontent.com/91793891/220863642-425b0a5f-7484-4a30-95a4-9f24b79bcb61.png)
-s23
![s20](https://user-images.githubusercontent.com/91793891/220863655-f4cc62a3-1d1b-40f1-9d34-ca784fc2c2f3.png)

작업한 내용
제가 ISSUE를 조매 잘못 팠네요. 105,106번 작업물이 한 번에 106번 branch에 올라가게 되었습니다. 반성합니다.
-인터넷 연결 안되었을 시, null Books > 0 Books 수정
-어플 실행 시, 서버 2번 통신 > 1번으로 수정 
-bookshelf 기기 대응 dimen 추가 (2가지 경우로 나눴으며 s10, s23 기준으로 실험해봄)
-함수 정리 : xml로 뺄 수 있는 부분은 빼서 간결한 코드 추구(완성 아니고 추구..)

PR 포인트
- dimen 같은 경우 한 번씩 봐보시는 것은 어떤가요.

2023-02-23 11:23 UTC, 2zerozu requested changes
작업하느라 고생했습니다
옵저브 함수만 나누면 될 것 같습니다~

2023-02-23 11:23 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
> +
IsServer를 옵저버 하는 함수인데 다른 내용들도 포함되어있어보입니다
함수를 구분하는 게 좋아보여요

2023-02-23 11:23 UTC, 2zerozu commented on app/src/main/res/values-xxxhdpi/dimen.xml
> +</resources>
고생하셨습니다 😭

2023-02-23 15:10 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
> +
분리해서 다시 pr 올렸습니다!

2023-02-24 06:14 UTC, 2zerozu approved these changes
고생하셨습니다 ~ 제목 수정해서 머지해주세요

2023-02-26 01:44 UTC, merged