#107 [refactor] 서버 도메인으로 변경
team-peekabook/Peekabook-AOS pull request #111
Opened 2023-02-23 11:01 UTC by hajeong67

관련 이슈
- closed #107 

작업 사진/동영상 (선택)
- 없서요

작업한 내용
- 서버 도메인으로 변경

PR 포인트
- 서버 도메인으로 변경

2023-02-23 11:19 UTC, 2zerozu requested changes
고생하셨습니다~

2023-02-23 11:19 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
>  import kotlinx.android.parcel.Parcelize
이거 deprecated 되었다네요. `kotlinx.parcelize`로 다시 import 해주세요

2023-02-23 11:19 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
> +    @SerialName("Book")
불필요한 SerialName입니다
SerialName의 역할을 알아보심 좋을 것 같네요

2023-02-23 11:19 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            deleteDetailUseCase.invoke(bookId.value!!)
`requireNotNull` 사용해주세요

2023-02-23 15:12 UTC, stellar-halo approved these changes
LGTM 고생했습니다!
나도 얼른 따라갈게,,

2023-02-24 06:37 UTC, 2zerozu requested changes
고생하셨습니다
코멘트 보고 수정하심 될 것 같습니다

2023-02-24 06:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
> +import kotlinx.android.parcel.Parcelize
여기는 왜 안 바꾸셨는지..

2023-02-24 06:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            getDetailUseCase.invoke(bookId)
`bookId` 파라미터로 받아오지 않고 뷰모델에 있는 `_bookId.value`를 `invoke`에 바로 꽂아도 될 것 같습니다

2023-02-24 06:48 UTC, 2zerozu requested changes

2023-02-24 06:48 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
> +            response.data!!.detail()
`requireNotNull` 사용해주세요

2023-02-24 06:56 UTC, 2zerozu requested changes

2023-02-24 06:56 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
>      fun getDetail(bookId: Int) {
불필요한 파라미터가 있네요
`bookId`는 쓰이지 않아보입니다

2023-02-24 08:20 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            getDetailUseCase.invoke(bookId)
```kotlin
    getDetailUseCase(bookId)
```

이렇게 사용해도 됩니다. @2zerozu @hajeong67

2023-02-24 08:29 UTC, l2hyunwoo reviewed
한번 참고해보세용

2023-02-24 08:29 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
> +    fun detail(): Detail = Detail(
도메인 데이터로 형변환을 하는 것이라면 toEntity, asDomain 등 좀 더 역할을 명시적으로 드러낸 함수명이면 다른 사람들도 보기 좋을 것 같아요

2023-02-24 08:29 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
> +    fun detail(): Detail = Detail(
그리고 이 친구가 왜 Parcelable이어야 하는지 알아보는 것도 좋을 것 같습니다. Parcelable의 경우에는 해당 데이터를 가진 객체를 프로세스 간 통신에 사용하기 위해 임시적으로 디스크/메모리에 저장하기 위해서 직렬화할 때 사용하는 유틸 기능입니다. 

> Container for a message (data and object references) that can be sent through an IBinder. A Parcel can contain both flattened data that will be unflattened on the other side of the IPC (using the various methods here for writing specific types, or the general [Parcelable](https://developer.android.com/reference/android/os/Parcelable) interface), and references to live [IBinder](https://developer.android.com/reference/android/os/IBinder) objects that will result in the other side receiving a proxy IBinder connected with the original IBinder in the Parcel.

[링크](https://developer.android.com/reference/android/os/Parcel) 들어가셔서 조금 더 자세하게 공부해보시면 좋을 것 같습니다.

2023-02-24 08:29 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
> +@Parcelize
도메인이 어떤 역할을 하는지 팀원분들과 같이 공부해보시면 좋을 것 같아요

2023-02-24 08:29 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            deleteDetailUseCase.invoke(requireNotNull(_bookId.value))
만약 _bookId.value가 null이면 다르게 처리하는 것도 (예를들면 early return이라던지) 좋을 것 같네요

2023-02-24 08:33 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
> +    fun detail(): Detail = Detail(
와 고맙습니다 놓친 부분이 있었네요 ㅠ `toDetail()`로 수정해주세요

2023-02-24 08:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
> +@Parcelize
> 도메인이 어떤 역할을 하는지 팀원분들과 같이 공부해보시면 좋을 것 같아요

와 나 왜 도메인에다가 `Serializable` 써놨지? 미쳤나봐 고마워 쇽샥이슈였다 고마워

2023-02-24 09:43 UTC, hajeong67 commented
> 한번 참고해보세용

훈련소 탈출을 추카!드립니다 코디 달아주셔서 감사!!! 공부할게

2023-02-27 10:37 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            getDetailUseCase.invoke(bookId)
> ```kotlin
> getDetailUseCase(bookId)
> ```

왜 invoke함수를 호출하지 않아도 되나요?

2023-02-27 10:53 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            getDetailUseCase.invoke(bookId)
@hajeong67 [이 링크](https://wooooooak.github.io/kotlin/2019/03/21/kotlin_invoke/)를 참고해보도록..!!

2023-02-27 11:05 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            getDetailUseCase.invoke(bookId)
> @hajeong67 [이 링크](https://wooooooak.github.io/kotlin/2019/03/21/kotlin_invoke/)를 참고해보도록..!!

오호~ 알아갑니다

2023-02-27 12:13 UTC, 2zerozu approved these changes
고생하셨습니당

2023-02-28 03:13 UTC, merged