#119 [refactor] 추천보기뷰 서버 도메인으로 변경
team-peekabook/Peekabook-AOS pull request #121
Opened 2023-03-01 07:44 UTC by hajeong67

관련 이슈
- closed #119

작업 사진/동영상 (선택)
- 노노

작업한 내용
- 추천보기뷰 서버 도메인으로 변경

PR 포인트
- 추천보기뷰 서버 도메인으로 변경

2023-03-01 09:32 UTC, stellar-halo approved these changes
LGTM 고생했서요!

2023-03-02 00:28 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다 코멘트 확인해주세요
그리고 마지막 커밋은 add가 아니라 fix가 더 어울려보입니다
레포지토리 주입에서 유즈케이스 주입으로 변경되었기 때문입니다

2023-03-02 00:28 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
>      val recommendingBook: List<Recommend>
데이터에서 사용되는 Recommend 데이터클래스는 RecommendEntity로 이름을 변경해서 사용하는 게 좋을 것 같습니다

2023-03-02 00:28 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
> +}
도메인 Recommend import해서 사용해주세요~

2023-03-05 16:20 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다.
일단 저번에 카톡에 설명했던 거 토대로 뜯어보시기 바랍니다..

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/RecommendResponse.kt
> +    )
현재 Recommend는 데이터 패키지에 있습니다.
우리는 데이터 엔티티를 도메인 엔티티로 바꾸는 것 때문에 변환하는 함수를 사용하는데 데이터 엔티티에서 데이터 엔티티로 바꿔주는 건 무의미해보입니다.

도메인에 Recommend를 만들고 그 도메인의 Recommend로 변환해주세요.
그럼 각자 안에 있는 recommendedBook과 recommendingBook들의 타입을 변환하는 함수가 필요하겠네요.
잘 뜯어보시길..

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
> +    override suspend fun getRecommend(): Result<Recommend> =
데이터의 Recommend입니다. Repository와 RepositoryImpl에서는 도메인 것을 사용해야합니다.

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/RecommendEntity.kt
> +data class RecommendEntity(
아~ 도메인에 Entity를 붙여줬군요..

도메인은 Recommend로, 데이터에는 RecommendEntity로 사용해주세요.

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/repository/RecommendRepository.kt
> +    suspend fun getRecommend(): Result<Recommend>
마찬가지로 data의 Recommend입니다.

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
> +    ListAdapter<RecommendEntity, BookRecommendAdapter.BookRecommendationViewHolder>(
음.. 위에는 분명 domain RecommendEntity를 만들어줬는데 왜 여기는 import가 data의 RecommendEneity로 되어있죠..? 희안하네요..

아무튼 어댑터에서는 domain 것이 사용되어야하는 게 맞습니다.

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
> +import com.sopt.peekabookaos.data.entity.RecommendEntity
뷰모델에서도 domain의 엔티티가 사용되는 게 맞습니다.

2023-03-05 16:20 UTC, 2zerozu commented on app/src/main/res/layout/item_recommend.xml
> +            type="com.sopt.peekabookaos.data.entity.RecommendEntity" />
xml에서도 도메인의 엔티티가 사용되는 게 맞습니다.

2023-03-09 18:16 UTC, 2zerozu approved these changes
고생하셨습니다!
앞으로 파이팅 해보자구요

2023-03-10 03:08 UTC, merged