#120 [refactor] bookshelf 서버 domain 변경
team-peekabook/Peekabook-AOS pull request #122
Opened 2023-03-01 09:45 UTC by stellar-halo

관련 이슈
- closed #120 

작업 사진/동영상 (선택)
- 없음

작업한 내용
- bookshelf 서버 domain으로 리픽토링

PR 포인트
- domain 변경을 맞게 했는가,,

2023-03-02 00:41 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다
데이터의 SelfService의 getPick()의 response의 `PickModify`도 데이터에서 사용하는 엔티티이기 때문에 `PickModifyEntity`를 데이터 엔티티에 하나 만들고 response를 `List<PickModifyEntity>`로 수정해서 사용해야 합니다. (그럼 그에 따라 데이터소스의 반환형도 달라지겠죠?) 도메인에서는 `PickModify` 그대로 사용하면 됩니다.

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
>      val books: List<Books>
데이터에서 사용되는 Picks와 Books는 각각 PickEntity와 BooksEntity로 따로 만들어서 사용해주세요
데이터에서 사용되는 데이터클래스 -> 뫄뫄Entity
도메인에서 사용되는 데이터클래스 -> 뫄뫄

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
> +    )
👍🏻

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
>      val books: List<Books>
여기도 마찬가지입니다

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
> +
불필요한 들여쓰기입니당

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
> +            getFriendShelfUseCase(userId.value!!)
requireNotNull 사용해주세요

2023-03-02 00:41 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
> +
불필요한 들여쓰기입니당

2023-03-02 01:05 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
>      val books: List<Books>
뫄뫄 구엽다

2023-03-02 01:07 UTC, hajeong67 approved these changes
굿!! 고생했어요

2023-03-03 12:19 UTC, l2hyunwoo reviewed
한번 확인해보세요 @stellar-halo cc. @2zerozu 

그리고 아키텍처를 불필요할정도로 세분화한다는 느낌이 있으면 왜 이걸 세분화해야하는 지 이유를 팀원들과 같이 논의해가면서 알아보고 어느정도로 구분지을지 결정하셔도 좋은 경험이 될 것 같다는 생각...!!!

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
>      val books: List<Books>
[여기 있는 내용](https://developer.android.com/topic/architecture/data-layer)도 한번 보는 건 어떨까요?

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
> +            requireNotNull(response.data).toFriendShelf()
쓰읍...이쯤되면 requireNotNull을 사용하는걸 떠나서 왜 nullable 데이터가 오는 지 한번 고려해야하지 않을까요?

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/MyShelf.kt
> +    val picks: List<Picks>,
Picks의 List가 어떤건지 잘 모르겠어... 복수형의 복수형이어서 어색해 보이는 것 같아

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
> +data class FriendShelf(
FriendShelf와 MyShelf가 거의 동일한 것 같은데 이런 경우에는 Shelf라는 공통 클래스에 나인지 아닌지만 구분하면 되지 않을까?

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/domain/usecase/GetMyShelfUseCase.kt
> +}
UseCase로 추상화하는 이유를 할 수 있을까?

2023-03-03 12:19 UTC, l2hyunwoo commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
> +            }
```suggestion
            }.onFailure(Timber::e)
```

이런식으로도 작성 가능

2023-03-10 11:26 UTC, hajeong67 approved these changes
수고했습니다!!!!

2023-03-10 11:26 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/DetailResponse.kt
> +        book = this.book.toBook()
오 제 부분 해주셨네요 감사합니다!

2023-03-10 11:26 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/FriendShelfResponse.kt
> +            friendListEntity.toFriendList()
언니 덕분에 이 부분 이제 이해완!!!!

2023-03-10 11:26 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/domain/usecase/PatchPickUseCase.kt
> +    suspend operator fun invoke(pickRequest: PickRequest) = shelfRepository.patchPick(pickRequest)
~Request 대신 파라미터 넣는 작업이 필요해보입니다!

2023-03-10 11:26 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/data/entity/BookEntity.kt
>      val author: String = ""
데이터 엔티티에 author가 초기화 되어 있군요!

2023-03-11 05:37 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다

NotificationAdapter에서
```
tvNotificationDate.text = getItem(position).createdAt.split("-")[1] + "월 " + getItem(position).createdAt.split("-")[2] + "일"
```
이 부분 하드코딩 말고 바꿔봅시다
제가 생각을 해봤는데, 데이터의 엔티티에서 도메인으로 바꿔주는 함수에서 split으로 나눠서 도메인 엔티티에 저장하고 그 데이터를 가져와서 사용하면 될 것 같아요

서버에서 보내주는 createAt을 보관하는 데이터 엔티티에서 도메인 엔티티로 변환하는 함수에서 원하는 형태 (예를 들어 2023년 1월 1일을 2023-1-1로 바꾼다는 등)로 변환해서 도메인의 createAt에 저장하면 될 것 같습니다.

+) `SimpleDateFormat`이라는 것도 있네요~ 함 찾아보고 적용할 수 있으면 이걸로 하면 될듯?

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Books.kt
> +    val book: Book
book 변수도 초기화해주세요

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Detail.kt
>      val book: Book
@hajeong67 하정이도 여기 book 초기화해서 사용해줘

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
> +    val books: List<Books>
여기도 다 초기화해주세요
리스트는 emptyList 사용하면 될거예요

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/MyShelf.kt
> +    val books: List<Books>
여기도 초기화

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Picks.kt
> +    val book: Book,
북 초기화해주세요

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
> +    suspend fun patchPick(pickRequest: PickRequest): Result<NoResponse>
나중에 Pick 도메인 수정할 때 도메인단에서 NoResponse 사용하는 거 수정해주세요

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
>                  )
나중에 리퀘스트 수정하기~

2023-03-11 05:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
> +            }.onFailure(Timber::e)
혹시 여기는 onSuccess시에 로직 수행이 없나요?

2023-03-11 09:46 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/Books.kt
> +    val book: Book
Book data class가 초기화 되어 있는데 book을 따로 초기화해야 하나요?

2023-03-11 09:52 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/domain/entity/FriendShelf.kt
> +    val books: List<Books>
위와 동일한 질문입니다..!

2023-03-11 09:52 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/domain/repository/ShelfRepository.kt
> +    suspend fun patchPick(pickRequest: PickRequest): Result<NoResponse>
NoResponse 따로 이슈 파서 해결하겠습니다!

2023-03-11 09:54 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
> +            }.onFailure(Timber::e)
서버에 성공적으로 보내면 액티비티가 종료되기 때문에 로직 수행이 없습니다! 그럼 그냥 onSuccess를 삭제해야 되나요.>?

2023-03-11 10:09 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
> +            }.onFailure(Timber::e)
> 서버에 성공적으로 보내면 액티비티가 종료되기 때문에 로직 수행이 없습니다! 그럼 그냥 onSuccess를 삭제해야 되나요.>?

액티비티가 종료되는 것 자체가 로직수행이라고 생각됩니다
onSuccess 시에 서버 상태변수를 true로 만들고 액티비티에서 그 상태변수를 옵저브해서 finish() 로직을 수행해야 하지 않을까 생각이 드네요

현재는 onFailure 시에도 finish()가 실행되는 로직입니다

2023-03-11 10:15 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
> +            }.onFailure(Timber::e)
아하 넵 확인했습니다

2023-03-11 11:33 UTC, 2zerozu approved these changes
고생하셨습니다~

2023-03-11 11:39 UTC, merged