#126 [refactor] 추천보기뷰 request 파라미터 변경
team-peekabook/Peekabook-AOS pull request #127
Opened 2023-03-11 08:24 UTC by hajeong67

관련 이슈
- closed #126 

작업 사진/동영상 (선택)
- x

작업한 내용
- 추천보기뷰 request 파라미터 변경

PR 포인트
- 추천보기뷰 request 파라미터 변경했습니다!

2023-03-11 14:23 UTC, 2zerozu requested changes
고생하셨습니다~

2023-03-11 14:23 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +        _bookData.value = requireNotNull(_bookData.value).copy(id = _bookId.value!!)
requireNotNull 사용해주세요

2023-03-11 14:23 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
>                  _isRecommendation.value = true
이부분 it이 무엇인지 잘 생각해보십쇼!

2023-03-11 17:12 UTC, 2zerozu approved these changes
고생하셨습니다
커밋에 신경을 더 써봅시다

2023-03-11 18:16 UTC, stellar-halo approved these changes
고생했어요~

2023-03-11 18:16 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommendation/RecommedationViewModel.kt
> +                requireNotNull(_friendData.value).id
kotlin은 기본적으로 not-null 하지만 LiveData는 Java 환경에서 구현되었기 때문에, nullable 입니다!
따라서 null check를 매번 해줘야 하는 번거로움이 있는 것입니다...

kotlin에 더 적합한 언어는 stateFlow 라고 합니다. 영주씨의 searchBookViewModel을 참고하시면 requireNotNull을 사용하지 않아도 null이 불가능하기 때문에 괜찮은 것을 알 수 있습니다.

궁금해서 찾아보다가 알게 되어 공유합니다.
https://stackoverflow.com/questions/46488442/is-it-possible-to-enforce-non-nullability-of-livedata-values

2023-03-11 18:20 UTC, stellar-halo requested changes

2023-03-11 18:20 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
> -                requireNotNull(response.data).toRecommendation()
이제 toRecommendation() 함수 안쓰니까 RecommendationResponse 에서 삭제해주시면 될 것 같습니다.

2023-03-13 09:02 UTC, stellar-halo approved these changes
수고했어요 :)

2023-03-13 18:00 UTC, merged