#131[ui] userInput xml 및 로직 구현
team-peekabook/Peekabook-AOS pull request #140
Opened 2023-03-17 09:29 UTC by stellar-halo

관련 이슈
- closed #131

작업 사진/동영상 (선택)
-자꾸 동영상 녹화가 안되길래 열받아서 핸드폰으로 녹화 했습니다. 화질 구지 양해..

작업한 내용
- userInput 뷰 xml 작업과 로직 구현 마쳤습니다.

PR 포인트
- 갤러리에서 이미지 불러오는 코드
- 입력 상태에 따른 버튼 비활성화
(중복 확인: 닉네임에 아무것도 입력되어 있지 않으면 비활성화 // 
확인: 닉네임, 한 줄 소개 모두 입력 되어 있지 않으면 비활성화)
- 중복 상태에 따른 경고 메세지
(중복확인: 중복확인 버튼을 눌렀을 때, 중복인 경우
확인: 중복이거나, 중복확인 버튼을 누르지 않은 경우)

2023-03-18 13:45 UTC, 2zerozu requested changes
고생하셨습니다
코멘트 확인해보세욥

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +        binding.lifecycleOwner = this
이거는 BindingActivity에 있는 거라 빼도 될 것 같네ㅐ요

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
이 뷰 백버튼 없애기로 했던 것 같은데 디자이너 언니들한테 물어보심이 좋을 것 같네요
+) 만약 백버튼이라고 하더라도 iv보다는 ImageButton을 사용해서 btn이 더 어울릴 것 같습니다
+) 백버튼은 연타가 불가능해서 setOnClickListener가 더 어울리겠네요

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +                startActivity(toMainActivity)
finish()가 필요해보입니다

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
bool이 의미하는 바가 명확하지 않습니다
다른 변수명이 더 어울리겠네요

그리고 enabled이랑 background는 xml에서 처리가 안 되나요?

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/drawable/shape_gray_fill_0_rect.xml
> +</shape>
음.. 이건 xml에서 background 컬러값을 직접 지정할 수 있지 않을까요?

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/drawable/shape_red_fill_0_rect.xml
> +</shape>
이것도

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +
```suggestion
```

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintTop_toTopOf="parent" />
백버튼이 없어진 걸로 알고 있는데, 만약 사용한다고 하더라도 ImageButton이 더 잘 어울릴 듯 싶습니다

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +
```suggestion
```

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintTop_toTopOf="parent" />
위에 basic이랑 같이 쓰는 건 불가능한가요? 몰라서 물어봅니다

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_goneMarginTop="30dp" />
이건 무슨 속성인가요?

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintDimensionRatio="8.0"
필요한 속성인가요??

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            android:inputType="textMultiLine"
닉네임에 멀티라인이 필요한가요?? 제 생각에는 다음 텍스트박스로 넘어가는 inputType이 더 어울려보입니다

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            tools:text="@string/iser_input_duplication_warning_message" />
user 오타난 것 같네요

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +
```suggestion
```

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            android:text="중복확인"
string으로 빼야할 것 같습니다

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintTop_toTopOf="@id/et_user_input_nickname" />
텍스트뷰로 박고 clickable로 조절하면 될 것 같습니다
이에 따라 불필요한 drawable은 삭제쿠다사이

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +
```suggestion
```

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_goneMarginTop="30dp" />
필요한 속성인가요??

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintBottom_toBottomOf="parent" />
이거도 텍스트뷰로 고고

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +
```suggestion
```

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="iser_input_duplication_warning_message">이미 사용 중인 닉네임 입니다</string>
iiiiiii

2023-03-18 13:45 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="iser_input_duplication_notify_message">닉네임 중복확인을 해주세요</string>
iiiiiii

2023-03-18 17:23 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
디자인쌤들이랑 의논하고 있으면 setOnClick으로 변경하고
없으면 더블 클릭시 앱 종료로 바꾸겠습니다.

2023-03-18 17:49 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
text로 최대한 처리해보겠습니다.

2023-03-18 18:08 UTC, stellar-halo commented on app/src/main/res/drawable/shape_gray_fill_0_rect.xml
> +</shape>
radius 때문에 drawble로 한 것인데 text로 처리하겠습니다!

2023-03-18 18:09 UTC, stellar-halo commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintTop_toTopOf="parent" />
이게 src로 해놓아도 profileImage 값 때문에 사진 골라주지 않으면 공백으로 보이더라고요.

2023-03-18 18:09 UTC, stellar-halo commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_goneMarginTop="30dp" />
이상한게 들어갔네요 머슥 지워주겟습니다.

2023-03-18 18:09 UTC, stellar-halo commented on app/src/main/res/layout/activity_user_input.xml
> +            android:inputType="textMultiLine"
넵!

2023-03-18 18:10 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="iser_input_duplication_warning_message">이미 사용 중인 닉네임 입니다</string>
우는 이모지가 없어 대신 손가락이 못마땅한 이모지로

2023-03-19 09:05 UTC, hajeong67 approved these changes
수고하셨습니다! xml에 사용한 속성들 참고할게용~!!

2023-03-21 05:26 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
> 디자인쌤들이랑 의논하고 있으면 setOnClick으로 변경하고
> 없으면 더블 클릭시 앱 종료로 바꾸겠습니다.

그거 있어도 없어도 더블클릭 필요할듯?? 안드로이드는 기본뒤로가기버튼이 있어서

2023-03-24 14:52 UTC, hajeong67 approved these changes
수고했습니다~!

2023-03-24 16:18 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다!
상태 관리 잘 하신 것 같군요 굿짭짭

1. 키보드 엔터키 액션
2. 다른 뷰 터치했을 때 키보드 hide 해주기
만 반영하심 될 것 같습니다~

2023-03-24 16:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +    }
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

2023-03-24 16:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +                viewModel.updateCheckMessage(viewModel.isNickname.value!!)
requireNotNull을 사용해봅시다

2023-03-24 16:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
> +        updateDuplicateButtonState(_isNickname.value!!)
requireNotNull을 사용해봅시다..!

2023-03-24 16:18 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintVertical_bias="0" />
무슨 기능인가요??

2023-03-24 16:24 UTC, stellar-halo commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintVertical_bias="0" />
bias 말씀하시는 건가요? chain의 가중치를 옮기는 것입니다! 보통 top, bottom을 걸게 되면 가중치가 1:1 로 설정되어 가운데에 오게 되지만 bias 를 0으로 설정 시에 top에만 붙게 됩니다.

2023-03-24 16:25 UTC, 2zerozu commented on app/src/main/res/layout/activity_user_input.xml
> +            app:layout_constraintVertical_bias="0" />
> bias 말씀하시는 건가요? chain의 가중치를 옮기는 것입니다! 보통 top, bottom을 걸게 되면 가중치가 1:1 로 설정되어 가운데에 오게 되지만 bias 를 0으로 설정 시에 top에만 붙게 됩니다.

오 쩌네요 확인 굿짭

2023-03-31 07:59 UTC, hajeong67 approved these changes
어푸르브가 늦어 죄송함니다 고생하셨습니다!

2023-03-31 07:59 UTC, hajeong67 commented on app/src/main/res/layout/activity_user_input.xml
> +            android:text="@{vm.isNickname == true? @string/user_input_unavailable_nickname_message : @string/user_input_available_nickname_message}"
굿굿!

2023-03-31 07:59 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +            if (System.currentTimeMillis() - onBackPressedTime >= WAITING_DEADLINE) {
이 줄은 무슨 의미인가요?

2023-04-02 07:59 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputActivity.kt
> +            if (System.currentTimeMillis() - onBackPressedTime >= WAITING_DEADLINE) {
요거 뒤로가기 연타 시간 구해서 연타 빨리하면 어플 꺼지는 건데, 지금 뺐어요!

2023-04-02 08:45 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다!

2023-04-02 08:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
> +        }
```suggestion
        binding.btnUserInputBack.setOnClickListener {                  findNavController().navigate(R.id.action_userInputFragment_to_socialLoginFragment)
        }
```
이렇게 써야 할 것 같습니다

2023-04-02 08:45 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputBottomSheetFragment.kt
> +class UserInputBottomSheetFragment(val itemClick: (Int) -> Unit) : BottomSheetDialogFragment() {
파라미터를 넘기는 방식보다 액티비티 뷰모델을 이용해봅시다요

2023-04-02 08:45 UTC, 2zerozu commented on app/src/main/res/layout/dialog_user_input_bottom_sheet.xml
> +
```suggestion
```

2023-04-02 08:45 UTC, 2zerozu commented on build.gradle
> +
```suggestion
```

2023-04-02 15:18 UTC, 2zerozu approved these changes
고생하셨습니다~~

2023-04-02 17:17 UTC, merged