#141 [ui] 신고하기뷰/뷰작업
team-peekabook/Peekabook-AOS pull request #148
Opened 2023-03-28 15:21 UTC by hajeong67

관련 이슈
- closed #141 

작업 사진/동영상 (선택)
-
![Screenshot_20230329_000614](https://user-images.githubusercontent.com/101049601/228285974-54f92845-8e01-4e48-b944-79bc00abf276.png)

![Screenshot_20230329_000648](https://user-images.githubusercontent.com/101049601/228285924-38722491-694d-47ad-9689-d41ec2d7c2e8.png)

작업한 내용
- 신고하기뷰의 뷰작업 했습니다.
- 라디오그룹과 라디오버튼 이용해서 구현했습니다.
- 다이얼로그와 연결했습니다.

PR 포인트
- 신고하기뷰의 ui

2023-03-29 19:24 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다
코멘트 참고해주세요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> -
이거 지우지 말아주세요!!

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +        </activity>
메타데이터 지워주고 화면세로고정도 넣어주세요
그리고 />로 마무리해주세요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
> +        }
함수로 빼주세요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/dialog_report_confirm.xml
> +            type="com.sopt.peekabookaos.presentation.report.ReportViewModel" />
데이터바인딩 쓰이는 곳이 없어보입니다

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportConfirmDialog.kt
> +        binding.vm = reportViewModel
데이터바인딩 쓰이는 곳이 없어보입니다

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportConfirmDialog.kt
> +            requireActivity().finish()
메인은 죽어있지 않고 살아있습니다
스택을 다시 생각해보세요!

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportViewModel.kt
> +    }
각 변수마다, 함수마다 들여쓰기 해주세요..

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportViewModel.kt
> +        Timber.d("${selectedReasonId.value}")
불필요한 주석은 지워주세요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_report.xml
> +            android:id="@+id/v_report_line_top"
v 말고 view로 써주세요 아래꺼도 다!

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_report.xml
> +            android:textColorHint="@color/peeka_g_1"
텍스트컬러 속성이 누락된 것 같네요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_report.xml
> +            tools:layout_editor_absoluteX="21dp" />
불필요한 속성같습니다!

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_report.xml
> +
```suggestion
```
들여쓰기가 하나 더 되어있네요

2023-03-29 19:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_report.xml
> +            android:id="@+id/btn_report_report"
텍스트인데 왜 btn?

2023-03-29 19:24 UTC, 2zerozu commented on icn_back.svg
> +</svg>
파일명 컨벤션이 맞지 않네요
혹시 같이 쓰이는 아이콘이 없나요?
꼭 추가해야 하는 아이콘이에요?

2023-03-30 09:38 UTC, stellar-halo approved these changes
영주씨가 꼼꼼하게 봐주셔서 저는 더 달 것이 안보이네요,,

2023-03-30 09:38 UTC, stellar-halo commented on app/src/main/res/layout/activity_report.xml
> +                android:layoutDirection="rtl"
흐-뭇

2023-03-31 07:35 UTC, 2zerozu commented on icn_back.svg
> +</svg>
정리하다보니 back버튼 동일한 게 존재하네요
이거 파일 지우고 가져다쓰세염

2023-04-03 00:24 UTC, 2zerozu requested changes
고생하셨습니다

2023-04-03 00:24 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +            android:exported="false"/>
화면회전 막아주세요

2023-04-03 00:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
> +        }
함수로 빼주세요

2023-04-03 00:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportViewModel.kt
> +    private val _selectedReasonId = MutableLiveData(1)
뷰모델에서만 사용되면 언더바는 지우고 사용해주세요
`selectedReasonId`

2023-04-03 00:24 UTC, 2zerozu commented on icn_back.svg
일단 컨벤션이 틀렸고, 불필요한 에셋같습니다
그리고 왜 svg로 들어갔는지는 모르겠네요
벡터 에셋으로 넣으면 xml파일로 들어가게 됩니다

2023-04-05 07:58 UTC, 2zerozu approved these changes
고생하셨습니다!

2023-04-05 07:58 UTC, merged