#6 [feat] recommend view 구현
team-peekabook/Peekabook-AOS pull request #15
Opened 2023-01-03 08:30 UTC by hajeong67

관련 이슈
- recommend view 구현

작업 사진/동영상 (선택)
-
![image](https://user-images.githubusercontent.com/101049601/210322030-4c30b7b5-f2bd-4f18-81e7-08e812abb0de.png)

작업한 내용
- recommend view 구현
- recyclerView 구현

PR 포인트
- 뷰 구현에 어색함이 없는지!!

2023-01-03 16:52 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다.
item은 전면적인 수정이 필요할 것 같아 당장 디스코드로 들어와주시면 감사하겠습니다.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
> +    BindingFragment<FragmentRecommendBinding>(R.layout.fragment_recommend) {
```suggestion
@AndroidEntryPoint
class RecommendFragment : BindingFragment<FragmentRecommendBinding>(R.layout.fragment_recommend) {
```
기존 것으로 되돌려주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/drawable/shape_white_fill_0_rect.xml
> +</shape>
```suggestion
```
shape을 만들 필요가 없어보입니다.
`android:background="@color/peeka_white"`를 이용해주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/drawable/shape_red_fill_0_rect.xml
> +</shape>
```suggestion
```
shape을 만들 필요가 없어보입니다.
android:background="@color/peeka_red"를 이용해주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/layout/fragment_recommend.xml
> +            android:layout_marginTop="20dp"
```suggestion
```

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/layout/fragment_recommend.xml
> +            app:layout_constraintTop_toBottomOf="@id/v_recommend_line" />
```suggestion
            app:layout_constraintBottom_toBottomOf="@id/tv_recommend_recommended"
            app:layout_constraintStart_toEndOf="@id/tv_recommend_recommended"
            app:layout_constraintTop_toTopOf="@id/tv_recommend_recommended" />
```

제약을 "추천받은 책"의 toptop과 bottombottom에 걸어주는 게 더 안정적일 것 같습니다.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/layout/item_recommend_recommended.xml
> +            android:layout_height="30dp"
```suggestion
            android:layout_height="wrap_content"
```
고정dp 지양해주세요. `tv_item_title`의 마진값으로 조절해주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/layout/item_recommend_recommended.xml
> +                android:id="@+id/tv_item_title"
```suggestion
                android:id="@+id/tv_item_recommend_title"
```
컨벤션 지켜주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
> +                "https://blog.kakaocdn.net/dn/cnCXEQ/btqO7jbSdwy/TDPQ03fpqWkRLr1bhNjQm1/img.jpg",
```suggestion
                "http://image.yes24.com/goods/90365124/XL"
```
더미데이터 사진 다 이걸로 바꿔주세요.

2023-01-03 16:52 UTC, 2zerozu commented on app/src/main/res/layout/item_recommend_recommended.xml
> +                android:layout_height="15dp"
```suggestion
                android:layout_height="0dp"
```
고정dp 사용 지양해주세요.

2023-01-03 19:20 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
> +        viewType: Int
어떤거 구현 말씀하신 걸까용

2023-01-04 06:30 UTC, stellar-halo approved these changes
고생하셨습니다!

2023-01-04 06:30 UTC, stellar-halo commented on app/src/main/res/layout/item_recommend.xml
> +            android:id="@+id/iv_item_recommend_redRect"
변수명이 잘못된 것 같아요!
`cl_item_recommend_(what)` 으로 변경하시는 건 어떤가요?

2023-01-04 06:32 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/recommend/BookRecommendAdapter.kt
> +        viewType: Int
> 어떤거 구현 말씀하신 걸까용

viewType이요~

2023-01-05 11:08 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다!

<img width="249" alt="image" src="https://user-images.githubusercontent.com/84129098/210766073-62c31af9-653b-4867-ba6b-6a8423592efa.png">

추천사 텍스트 위치 수정만 하면 될 것 같습니다 ~

2023-01-05 11:08 UTC, 2zerozu commented on app/src/main/res/layout/item_recommend.xml
> +            android:layout_height="30dp"
고정dp 수정해주세요

2023-01-05 11:36 UTC, 2zerozu requested changes

2023-01-05 11:36 UTC, 2zerozu commented on app/src/main/res/layout/fragment_recommend.xml
> +            android:layout_marginTop="46dp"
탑 마진 확인해주세요.

2023-01-05 12:23 UTC, hajeong67 commented on app/src/main/res/layout/item_recommend.xml
> +            android:layout_height="30dp"
넵

2023-01-06 12:35 UTC, 2zerozu approved these changes
LGTM ^__________^

2023-01-06 12:35 UTC, merged