[ui] 차단사용자 관리뷰
team-peekabook/Peekabook-AOS pull request #161
Opened 2023-04-02 17:45 UTC by hajeong67

관련 이슈
- closed #149 

작업 사진/동영상 (선택)
-
![Screenshot_20230403_023624](https://user-images.githubusercontent.com/101049601/229369784-efd02c98-5a38-4f8b-abf0-ba71c27f6d57.png)

작업한 내용
- 차단사용자 관리뷰 리사이클러뷰

PR 포인트
-  리사이클러뷰 구현

2023-04-02 18:04 UTC, stellar-halo reviewed
현재 작업하고 있는 브랜치가 최신 브랜치를 반영하지 않은 것 같아요! 꼭 Pull받고 작업해주세요~

2023-04-02 18:04 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockViewModel.kt
> +            FriendList(4, "이영주", "https://nhim.splf.in/image/acnh/animal/Agent%20S.png")
❤

2023-04-02 18:04 UTC, stellar-halo commented on app/src/main/res/layout/item_block.xml
> +            name="friend"
friendList로 바꾸시는 것은..? 자그마한 제안입니다

2023-04-02 18:06 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
> +    private const val USER_ID = "1"
풀을 늦게 받았습니다요 ㅠㅠ 풀받고 다시 피알 날렸어요

2023-04-02 18:14 UTC, 2zerozu commented on app/src/main/res/layout/item_block.xml
> +            name="friend"
저라면 data라고 쓸 것 같습니다

2023-04-03 00:35 UTC, 2zerozu requested changes
고생하셨습니다

2023-04-03 00:35 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
세로고정 해주세요

2023-04-03 05:48 UTC, stellar-halo approved these changes
고생했어요!~

2023-04-05 05:32 UTC, 2zerozu approved these changes
고생~

2023-04-05 05:32 UTC, merged