[feat] 차단하기뷰/다이얼로그 연결&서버
team-peekabook/Peekabook-AOS pull request #183
Opened 2023-04-10 09:47 UTC by hajeong67

관련 이슈
- closed #165 

작업 사진/동영상 (선택)
-
https://user-images.githubusercontent.com/101049601/230877370-3465841b-39fe-4a6b-9335-e177a0c9d3df.mp4

작업한 내용
- 다이얼로그 연결
- 차단리스트 조회(get)
- 차단리스트 해제(delete)

PR 포인트
- 푸쉬하고 생각해보니.. 차단해제 버튼을 눌렀을때 바로 차단목록이 꺼지면 안되고 유지되는 것이 나을 것 같아 추후 수정하겠습니다.

2023-04-10 11:24 UTC, stellar-halo requested changes

2023-04-10 11:24 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockActivity.kt
> +                finish()
여기를 blockViewModel.getBlock()으로 바꾸면 안꺼지고 데이터 갱신될 거 같아요. 어짜피 QA때 걸릴 거 간단한 건데 수정합시다!

2023-04-10 14:18 UTC, 2zerozu requested changes
고생하셨습니다

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockActivity.kt
> +    private val blockAdapter = FriendBlockAdapter(showInitBlockDialog = ::initBlockDialog)
👍🏻👍🏻👍🏻👍🏻👍🏻

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockDeleteDialog.kt
> +        const val DEFAULT = "default"
default도 밖에서 쓰이나요? private로 해줘도 되는건듯?

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockDeleteDialogContent.kt
> +}
BlockDeleteDialogContent를 만들어준 이유를 알 수 있을까요?
공유해서 쓰는 다이얼로그가 아닌데 스트링을 이렇게 박아준 이유가 궁금합니다!
그냥 xml의 text속성에 바로 string 박아도 되지 않을까 싶어서..

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockViewModel.kt
> +                    _isServerStatus.value = true
isServerStatus이 필요없어보입니다!
isServerStatus 대신 blockData를 observe해서 blockData가 업데이트 될 때마다 adapter에 submitList에 observe의 it(blockData)를 넣으면 더 좋은 로직이 될 것 같습니다

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/FriendBlockAdapter.kt
> +        private val showInitBlockDialog: (FriendList, Int) -> Unit
showInitBlockDialog보다는 showBlockDialog 또는 initBlockDialog가 더 자연스러워보입니다

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/FriendBlockAdapter.kt
> +            binding.tvBlockCancel.setOnClickListener {
여러번 클릭 가능해보입니다. 싱글클릭리스너로 바꿔봅시다

2023-04-10 14:18 UTC, 2zerozu commented on app/src/main/res/layout/dialog_block_delete.xml
> +            android:text="@{block.title}"
공유해서 쓰이는 다이얼로그가 아니라면 text에 바로 string박는 게 더 좋을 것 같습니다

2023-04-10 15:21 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockActivity.kt
> +        }
```suggestion
        blockViewModel.blockData.observe(this) { blockData ->
            blockAdapter.submitList(blockData)
        }
```

2023-04-12 15:48 UTC, 2zerozu approved these changes

2023-04-12 15:53 UTC, merged