#175 신고하기뷰 서버
team-peekabook/Peekabook-AOS pull request #184
Opened 2023-04-10 11:32 UTC by hajeong67

관련 이슈
- closed #175

작업 사진/동영상 (선택)
-

https://user-images.githubusercontent.com/101049601/230893657-de71ebd7-b729-4fe6-94ea-2c35a270d62e.mp4

작업한 내용
- post 서버통신

PR 포인트
- 없습니다~!!

2023-04-10 12:55 UTC, stellar-halo requested changes

2023-04-10 12:55 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
> +                        1 -> startActivity(Intent(requireActivity(), ReportActivity::class.java))
연결 감사합니다

2023-04-10 12:55 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
> +    }
isReport는 postReport를 하고 나서 변화되는 값인데, 성공하면 왜 다시 서버 통신을 하게 되나요?
로직 수정이 필요해 보입니다.

2023-04-10 14:22 UTC, 2zerozu reviewed
강희 코리 반영되면 어푸할게요

2023-04-12 14:37 UTC, stellar-halo approved these changes

2023-04-12 15:45 UTC, 2zerozu approved these changes

2023-04-12 15:46 UTC, merged