#178 [feat] 마이페이지 서버
team-peekabook/Peekabook-AOS pull request #187
Opened 2023-04-10 13:29 UTC by hajeong67

관련 이슈
- closed #178 

작업 사진/동영상 (선택)
-
![KakaoTalk_20230410_222713991](https://user-images.githubusercontent.com/101049601/230910298-2da0c998-b049-401b-a8c2-0bcc0b1287ed.jpg)

작업한 내용
- 마이페이지 서버 연결 get

PR 포인트
- 없습니다

2023-04-10 14:40 UTC, 2zerozu requested changes
고생하셨습니다

2023-04-10 14:40 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
> +                    _isServerStatus.value = true
isServerStatus는 무슨 역할인가요? 프래그먼트에서 따로 옵저브하는 게 없어요

2023-04-10 14:43 UTC, stellar-halo approved these changes
고생했습니다

2023-04-10 15:37 UTC, 2zerozu reviewed
[개인정보 보호 정책 & 서비스 이용 약관](https://interesting-door-b57.notion.site/d00db57d23414511ad8ec1f2f24c230a) 이 링크도 추가연결해주세욤

2023-04-12 15:53 UTC, 2zerozu requested changes
풀받으면 SelfIntro가 User로 바뀔거라 머지컨플릭트 잘 해주세요

2023-04-12 15:53 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
> +    }
val로 바꾸고 링크 string으로 빼고 사용해주시고..

2023-04-12 15:53 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
> +                    Timber.d("get 서버통신 성공")
불필요한 팀버 지우기

2023-04-12 16:16 UTC, 2zerozu approved these changes

2023-04-12 16:16 UTC, merged