#151 [ui&feat] 프로필수정 ui, 서버
team-peekabook/Peekabook-AOS pull request #192
Opened 2023-04-13 10:31 UTC by hajeong67

관련 이슈
- closed #151 

작업 사진/동영상 (선택)
-
프로필 사진 관련
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/a580f82e-afcb-4522-89ac-0c137b9bdbd3

닉네임 중복확인 버튼 관련
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/b543de91-e3ff-4472-89a6-5b446c8867fd

체크문구가 뜨고 중복확인 버튼을 눌러 중복확인을 해도 문구가 사라지지 않는 오류 수정 && 체크버튼 누를 때 키보드 숨기기
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/c0ecb63f-fdde-4cd7-b820-fddb284eaf5f

닉네임 수정하지 않고 한줄소개만 수정하고 체크버튼 누를 때, 중복확인 문구 뜨는 오류 수정
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/a810fa78-3908-41a9-8e7c-d1ac8cca5a28

작업한 내용
- 바텀시트 연결
- 카메라, 갤러리 연결
- 닉네임 중복확인 api
- 마이페이지에서 프로필이미지, 닉네임, 한줄소개 데이터 넘겨받기
- 체크버튼 활성화
- 카메라 권한 설정 토스트 띄우기
- 기본이미지 변경
- 프로필수정 (patch) 서버통신 api

----수정사항----

- 체크버튼 눌렀을때 메인 activity로 가는것 마이페이지 Fragment로 가도록 변경(onResume()사용)
- 디쟌쌤에게 터치영역 수정된 새로운 에셋 요청하여 마이페이지에 수정 에셋 거리 조절
- 정규표현식(한글, 영어, 숫자만 입력 가능하도록) 변경
- 피그마 6/17 업뎃본: 마이페이지에 '오픈소스 라이브러리' 추가
- 프로필 사진이 있는 채로 변경하지 않고 닉네임이나 한줄소개 변경 후 완료 버튼 누를 때, 기본 이미지로 변경되는 오류 수정
- 프로필 사진 삭제 후 완료 버튼을 누를 때, 기본이미지 적용되지 않는 오류 수정
- 초기에 중복확인 버튼이 비활성화 되도록 수정
- 체크 버튼 누를 때 중복확인 상태가 확인 되어야만 patch함수 실행되도록 수정
- 체크버튼 누를 때 키보드 숨기기
- 체크문구가 뜨고 중복확인 버튼을 눌러 중복확인을 해도 문구가 사라지지 않는 오류 수정
- 닉네임 수정하지 않고 한줄소개만 수정하고 체크버튼 누를 때, 중복확인 문구 뜨는 오류 수정

PR 포인트
- 체크버튼 누를 때 키보드 숨기기
- 체크문구가 뜨고 중복확인 버튼을 눌러 중복확인을 해도 문구가 사라지지 않는 오류 수정
- 닉네임 수정하지 않고 한줄소개만 수정하고 체크버튼 누를 때, 중복확인 문구 뜨는 오류 수정

2023-04-13 11:29 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +                    }
선택지가 하나 더 늘어났으므로 미래의 자신을 위해 구현해야 할 것을 //TODO로 적어주세요

2023-04-13 11:29 UTC, stellar-halo commented on app/src/main/res/layout/dialog_profile_modify_botton_sheet.xml
> +
여기도 구현되지 않은 부분을 주석처리로 써두시는게 어떤가요?

2023-04-13 11:29 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
이거 뭔가요?

2023-04-13 11:53 UTC, hajeong67 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
> 이거 뭔가요?

삭제하겠습니다

2023-04-14 07:11 UTC, 2zerozu requested changes
고생하셨습니다

2023-04-14 07:11 UTC, 2zerozu commented on app/src/main/res/drawable/ic_profile_modify_add.xml
> +</vector>
어디서 쓰이나요?

2023-04-14 07:11 UTC, 2zerozu commented on app/src/main/res/layout/activity_profile_modify.xml
> +            android:hint="닉네임은 6자까지 쓸 수 있어요!"
string으로 빼주세요

2023-04-14 07:11 UTC, 2zerozu commented on app/src/main/res/layout/activity_profile_modify.xml
> +            android:hint="한 줄 소개는 40자까지 쓸 수 있어요!"
string으로 빼주세요

2023-04-14 07:11 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +
@stellar-halo UserInput이랑 겹치는 부분이 많아보이는데 합쳐서 사용하는 건 어떻게 생각혀

2023-04-28 09:15 UTC, hajeong67 commented on app/src/main/res/drawable/ic_profile_modify_add.xml
> +</vector>
> 어디서 쓰이나요?

만들었다가 이미 존재하는 파일로 대체했는데 삭제를 안했네요 삭제하겠습니다

2023-04-28 10:21 UTC, 2zerozu requested changes
오랜만에 작업이네용 고생하셨습니다

2023-04-28 10:21 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +            }
로직 수정이 안 됐습니다!

2023-04-28 10:21 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
> +    val isModifyStatus: LiveData<Boolean> = _isModifyStatus
사용되지 않는 변수입니다

2023-05-02 06:42 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +            }
> 로직 수정이 안 됐습니다!

오호.. 다시 고민해보겠습니다!

2023-05-02 06:51 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
> +    val isModifyStatus: LiveData<Boolean> = _isModifyStatus
> 사용되지 않는 변수입니다

잘못쓰이고 있는것 같습니다 수정할게요!

2023-05-03 11:02 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +
@2zerozu 이제봤네요 죄송 ,,, 상관 없을 듯 해요

2023-05-05 06:10 UTC, 2zerozu requested changes
고생하셨습니다

2023-05-05 06:10 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +            profileModifyViewModel.introduce.value = binding.etProfileModifyIntroduce.text.toString()
1. 캡슐화가 안 되어있습니다 (캡슐화가 뭔지, get/set에 대해 공부해보기)
2. 양방향데이터바인딩에 대해 더 공부해보기

다시 생각해보길!

2023-05-07 04:17 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +            profileModifyViewModel.introduce.value = binding.etProfileModifyIntroduce.text.toString()
> 1. 캡슐화가 안 되어있습니다 (캡슐화가 뭔지, get/set에 대해 공부해보기)
> 2. 양방향데이터바인딩에 대해 더 공부해보기
> 
> 다시 생각해보길!

확인완 했습니다! nickname, introduce가 xml상에서 양방향 데이터 선언되어있고, ViewModel에서 MutableLiveData이므로 사용자가 입력할 때 마다 입력값이 변경되네요! 저 코드는 불필요한 것 같아 삭제하겠습니다~!

2023-05-07 15:43 UTC, stellar-halo requested changes

2023-05-07 15:43 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +                    2 -> binding.ivProfileModifyImage.setImageResource(R.drawable.ic_user_input_profile)
기본 이미지로 변경하는 item index 같은데, 이 때에는 넘겨주는 UserDate 값을 null로 변경하는 코드가 추가로 필요해 보입니다.

2023-06-03 09:27 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyBottomSheetFragment.kt
> +    }
이번엔 이렇게 구현하는 걸로 하구 .. 담에는 더 좋은 방법을 찾아봅시다!!

2023-06-03 09:28 UTC, 2zerozu commented on .idea/kotlinc.xml
이거는 왜 추가했는지.... 지워주라~~

2023-06-25 23:45 UTC, stellar-halo approved these changes
고생하셨습니다!

2023-06-25 23:45 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +                    binding.ivProfileModifyImage.setImageResource(R.drawable.ic_user_input_profile)
이 줄 삭제해도 null로 파일이 바뀌어서 기본 이미지로 보일 것 같은데  안바뀌나요?

2023-06-25 23:45 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
> +        if (requestCode == 1 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
저도 0,1,2로 하긴 했는데 나중에 코드 가독성을 위해서 companion으로 빼서 하면 좋을 것 같아요! 저도 바꿀 생각입니다~

2023-06-26 02:37 UTC, devxsby commented
LGTM. 🍀

2023-06-26 18:07 UTC, 2zerozu requested changes
고생하셨습니다

2023-06-26 18:07 UTC, 2zerozu commented on app/src/main/res/layout/fragment_my_page.xml
> +            android:text="오픈소스 라이브러리"
string 리소스를 사용합시다

2023-06-26 18:10 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
> +            postDuplicateUseCase(requireNotNull(nickname.value)).onSuccess { check ->
.onSuccess는 가독성을 위해 한 칸 밑에 써줄까욥

2023-06-28 13:04 UTC, 2zerozu reviewed
현재 닉네임을 수정하고 중복확인 버튼을 누르지 않은 상태에서 체크버튼을 누르면 메세지가 키보드에 가려 메세지가 뜨지 않습니다!
체크버튼을 누를 시에 키보드를 숨기는 로직을 구현해야 할 것 같아요
아니면 해당 영상을 기획한테 보여주고 닉네임 중복확인 에러메세지 위치를 수정하거나 해야 할 것 같네요
+) 현재 중복확인눌러도 중복확인 에러메세지 안사라집니다~
+) 닉네임 수정 안 하고 한 줄 소개만 수정했는데도 중복확인 에러메세지 뜹니다

2023-06-28 18:50 UTC, merged