Feature/#19 UI feat detail view
team-peekabook/Peekabook-AOS pull request #22
Opened 2023-01-06 13:55 UTC by hajeong67

관련 이슈
- closed #19 

작업 사진/동영상 (선택)
-

작업한 내용
- 상세뷰 구현

PR 포인트
- 상세뷰 구현

2023-01-06 15:00 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다.

1. 삭제랑 편집 버튼이 없네요! 추가해주세요.
2. xml 린트가 안 맞습니다. 코드 정리 해주세요.
3. 한마디와 메모에 값이 없을 경우에 visibility 처리하는 것보다는 text를 다르게 띄워주는 방향으로 가는 게 좋을 것 같습니다. (text값이 null이나 empty일 때 text와 textColor를 다르게 띄운다.)
4. 한마디와 메모의 백그라운드 컬러가 잘못됐습니다.
5. string값은 추출해서 사용해주세요.
+) 6. maxLength 넣어주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +        </activity>
```suggestion
        <activity
            android:name=".presentation.detail.DetailActivity"
            android:exported="false"/>
```
meta-data 제거하고 </activity>는 />로 바꿔주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
> +            memo = null
```suggestion
            description ="",
            memo =""
```
빈값으로 바꿔주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:layout_marginStart="18dp"
마진값 다시 확인해주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            app:layout_constraintTop_toTopOf="parent"
parent 말고 `ic_detail_back`에 제약 걸고 탑마진값 수정해주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:text="한 마디"
string으로 빼주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:text="작성된 한 마디가 없습니다"
string으로 빼주세요.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            app:layout_constraintStart_toStartOf="parent"
start랑 end 제약 `tv_detail_getContent`에 걸어주고 수평마진 지워주세요.
(아래 모든 뷰들 포함)

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:background="@drawable/shape_whitefill_redline_0_rect"
백그라운드값이 잘못된 것 같습니다.

2023-01-06 15:00 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
불필요한 string은 제거해주세요.

2023-01-07 06:31 UTC, 2zerozu requested changes
작업하느라 고생하셨습니다.

마진값 확인해보고 다시 올려주세요.

2023-01-07 06:31 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait" />
👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

2023-01-07 06:31 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
> +            if (it.description?.isNullOrEmpty() == true) {
👍🏻👍🏻👍🏻

2023-01-07 06:31 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
> +                with(binding) {
👍🏻👍🏻👍🏻

2023-01-07 06:31 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            app:layout_constraintTop_toTopOf="@id/ic_detail_back"
제약 확인해주세요. top-top에 걸었습니다.

2023-01-07 06:31 UTC, 2zerozu commented on app/src/main/res/drawable/shape_beigefill_redline_0_rect.xml
> +</shape>
불필요한 drawable입니다.

2023-01-07 11:30 UTC, 2zerozu approved these changes
LGTM ^__________^

2023-01-07 11:45 UTC, stellar-halo approved these changes
고생하셨어요! 😁

2023-01-07 11:45 UTC, stellar-halo commented on app/src/main/res/layout/activity_detail.xml
> +            android:text="@string/tv_detail_content"
요런 TextView 안에 `tools:text `로 값 넣어서 ,bulid 하기 전에 확인해보시는 건 어떨까요?

2023-01-07 11:59 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:text="@string/tv_detail_content"
> 요런 TextView 안에 `tools:text `로 값 넣어서 ,bulid 하기 전에 확인해보시는 건 어떨까요?

이친구는 데이터바인딩으로 넣어준 것이 아니라서 잘 보입니다!

2023-01-07 12:15 UTC, merged