#273[feat] 앱 버전이 맞지 않을 경우, 업데이트 화면 뜨게 하기
team-peekabook/Peekabook-AOS pull request #274
Opened 2023-11-02 20:11 UTC by stellar-halo

관련 이슈
- closed #273 

작업 사진/동영상 (선택)
-

작업한 내용
- 스플래시 화면에서 앱 버전이 맞지 않을 경우, 업데이트 화면으로 뜨게 하여 플레이 스토어로 연결하기

PR 포인트
- 제 모든 코드가 요주의 인물 같습니다.. 특별히 새롭게 쓰인 것은 없습니다.
- 현재 서버가 내려주는 값은 1.0.1 저희 어플은 1.0.2 이므로 업데이트 화면이 뜨는 게 정상입니다.

2023-11-02 23:24 UTC, 2zerozu requested changes
고생하셨습니다
코멘트 참고해주세요!

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/VersionResponse.kt
> +    val iosForceVersion: String,
현재 우리는 iOSForceVersion이라는 변수가 필요하지 않습니다!
json에는 `ignoreUnknownKey`라는 키워드가 있는데 다음에 공부해서 리팩토링 해봅시다

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/VersionResponse.kt
> +    val imageUrl: String,
imageUrl이 현재 뷰에는 쓰이지 않는데 nullable 변수인지 서버한테 물어보면 좋을 것 같네요

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +    private fun initDataObserver() {
클린코드에서는 의미 있는 함수명 및 변수명을 사용하라고 안내하고 있습니다
불용어는 지양해주세요!

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="force_update_content">어느 기능이 추가되었는지 알아볼까요?</string>
아마 이 내용을 서버에서 보내주기 때문에 string으로 저장하는 것이 아닌 서버통신에서 받아온 것을 사용하면 될 것 같네요

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/res/layout/activity_force_update.xml
> +                android:text="@string/force_update_content"
데이터바인딩이 필요해보입니다

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +        val isPreviousVersion = appVersionName != splashViewModel.versionName.value
음.. 현재는 버전이 같지 않을 때 뜨는 거 같은데 a.b.c에서 a나 b가 ++됐을 경우만 강제업데에트에 해당됩니다
c가 ++되면 강제업데이트에 해당되지 않으니 참고해서 로직 다시 짜면 좋겠네요

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    }
무조건 실행하기 때문에 init에 넣어줘도 좋을 것 같네요

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +        splashViewModel.getVersion()
Handler 함수가 없어지면 스플래시 뷰가 없어집니다
Delayed 안에 함수를 호출해주세요

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    val isVersionStatus: LiveData<Boolean> = _isVersionStatus
UiState라는 데이터클래스를 만들어서 변수를 하나에 관리하는 건 어떨까요?

2023-11-02 23:24 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +            Handler(Looper.getMainLooper()).postDelayed({ checkSplashState() }, DURATION)
이 함수는 무조건 떠야합니다😄

2023-11-03 00:23 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    val isVersionStatus: LiveData<Boolean> = _isVersionStatus
isVersionStatus보다는 isForceUpdate가 더 직관적인 것 같은데 어떻게 생각하시나요?

2023-11-03 02:10 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/forceUpdate/ForceUpdateActivity.kt
> +    lateinit var intentToPlayStore: Intent
없습니다 그냥 놓친 것뿐입니다..

2023-11-03 02:10 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/data/entity/response/VersionResponse.kt
> +    val imageUrl: String,
꼼꼼한 핃백 감사합니다

2023-11-03 02:11 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +    private fun initDataObserver() {
Observer가 무조건 data를 보니까 불용어라고 하신 걸까요?

2023-11-03 02:12 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="force_update_content">어느 기능이 추가되었는지 알아볼까요?</string>
넵!🫡

2023-11-03 02:13 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +            Handler(Looper.getMainLooper()).postDelayed({ checkSplashState() }, DURATION)
플레이스토어 가도 자꾸 그 위에 온보딩 화면이 떠서 넣어버렸더니 안떠서 좋아라 했는데, 제가 스플래시까지 날려버렸군요..? 하핫 고쳐보겠습니다

2023-11-03 02:15 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    val isVersionStatus: LiveData<Boolean> = _isVersionStatus
당장은 여기에서만 쓰이니 안만드는게 좋겠다고 생각했는데, 나중엔 다른 곳에서도 쓰일 수도 있겠네요..!

2023-11-03 03:09 UTC, hajeong67 approved these changes
강희언니 수고많았어 영주언니 꼼꼼한 리뷰 보고 많이 배우고 갑니다..!!!

2023-11-03 03:09 UTC, hajeong67 commented on app/src/main/java/com/sopt/peekabookaos/data/service/ForceUpdateService.kt
> +    @GET("user/v1/version")
👍👍👍

2023-11-03 08:59 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +    private fun initDataObserver() {
> Observer가 무조건 data를 보니까 불용어라고 하신 걸까요?

data 자체가 불용어입니다!

2023-11-03 09:02 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    val isVersionStatus: LiveData<Boolean> = _isVersionStatus
음 .. 개인적으론 코딩스타일인 것 같아서 다음에 uiState 공부하고 적용해보면 좋을 것 같아요

2023-11-03 14:33 UTC, stellar-halo commented on app/src/main/res/layout/activity_force_update.xml
> +                android:text="@string/force_update_content"
현재는 고정문구라하여 데바 안하겠습니다!

2023-11-03 14:33 UTC, stellar-halo commented on app/src/main/res/values/strings.xml
> +    <string name="force_update_content">어느 기능이 추가되었는지 알아볼까요?</string>
지금 전부 고정문구라네요!

2023-11-05 13:28 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    val isVersionStatus: LiveData<Boolean> = _isVersionStatus
서버 통신 변수명이니까 status가 들어가는 것이 좋아보여 isForceUpdateStatus로 변경했습니다

2023-11-05 15:05 UTC, 2zerozu requested changes
고생선배.... 우리 뷰모델 라이브데이터 써줘잉

2023-11-05 15:05 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +    }
isForceUpdateStatus가 success일 때.. 뭔가 말이 이상해보입니다ㅠ

2023-11-05 15:05 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +            previousMajor != splashViewModel.majorVersion || previousMinor != splashViewModel.minorVersion
해당 부분은 비즈니스 로직으로 뷰모델에서 진행되면 더 좋을 것 같네요

2023-11-05 15:05 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +            previousMajor != splashViewModel.majorVersion || previousMinor != splashViewModel.minorVersion
해당 부분은 비즈니스 로직으로 뷰모델에서 진행되면 더 좋을 것 같네요

2023-11-05 15:05 UTC, 2zerozu commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +        }
when문으로 처리하면 더 직관적일 것 같아요

2023-11-05 15:05 UTC, 2zerozu commented on app/src/main/res/layout/activity_force_update.xml
> +            name="vm"
저도 나중에 리팩토링 할거지만, 클린코드에서는 약어를 지양하라고 합니다.
vm이라 하면 view model인지, virtual machine인지 혼동이 올 수 있습니다 (실제로 경험해봄)
viewModel이라고 명시하는 건 어떨까요?!

2023-11-05 15:05 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +        const val LATEST_VERSION = "latest version"
Forceupdateactivity에서 써줍니다

2023-11-05 15:08 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
> +    }
isForceUpdate 로 바꾸겠습니다

2023-11-05 15:11 UTC, stellar-halo commented on app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
> +    lateinit var minorVersion: String
액티비티에서 observe 합니다.

2023-11-06 05:10 UTC, 2zerozu approved these changes
고생했어~~

2023-11-06 05:10 UTC, merged